ci: turn off travis ci

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,27 +4,26 @@ node_js:
   - lts/*
 
 cache: npm
+# before_deploy:
+#   - if ! [ $NPM_PUBLISH ];
+#     then
+#     NPM_PUBLISH=true;
+#     npm run build;
+#     else
+#     cd demo; npm i get-some-cool-emojis; npm run build
+#     fi
 
-before_deploy:
-  - if ! [ $NPM_PUBLISH ];
-    then
-    NPM_PUBLISH=true;
-    npm run build;
-    else
-    cd demo; npm i get-some-cool-emojis; npm run build
-    fi
+# deploy:
+#   - provider: npm
+#     email: michael19920327@gmail.com
+#     api_key: $NPM_TOKEN
+#     skip_cleanup: true
+#     on:
+#       tags: true
 
-deploy:
-  - provider: npm
-    email: michael19920327@gmail.com
-    api_key: $NPM_TOKEN
-    skip_cleanup: true
-    on:
-      tags: true
-
-  - provider: pages
-    github_token: $GITHUB_TOKEN
-    skip_cleanup: true
-    local_dir: demo/dist
-    on:
-      tags: true
+#   - provider: pages
+#     github_token: $GITHUB_TOKEN
+#     skip_cleanup: true
+#     local_dir: demo/dist
+#     on:
+#       tags: true
